import assert from 'node:assert/strict';
import {ensureScene,pixelPoints,makeProp,validateScene,clampPosition} from './dist/layout-model.mjs';
import {tailoredInitial,validateProject,calculate,newSegment,bankFor,recommendSections} from './dist/model.mjs';
import {connectWire} from './dist/wiring-model.mjs';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} differs from ${b}`);
const p=tailoredInitial();validateProject(p);
const seed={...newSegment(),count:200,watts:.3,spacing:0,leadM:5,leadAwg:18};
const flood={...newSegment('flood'),count:1,watts:10,leadM:0};
p.chains=[{id:'test',name:'200 seeds + 10 W flood',controller:'c1',port:1,segments:[seed,flood]}];
p.controllers[0].bankM=[0,0];p.brightness=100;
let r=calculate(p);near(r.watts,70);near(r.psus.p1.amps,70/12);near(r.chains.test.minV,12-1.2220833333333334);assert.equal(r.channels,603);assert.equal(r.chains.test.end,603);
seed.spacing=.1;seed.stringAwg=18;flood.watts=.001;
r=calculate(p);near(r.chains.test.segments[0].inputV-r.chains.test.segments[0].endV,2.084525+2*.02095*.1*199*(.001/12));
seed.spacing=0;flood.watts=10;flood.inject=true;flood.psu='p3';flood.distro='d1';flood.feedM=2;flood.feedAwg=18;
r=calculate(p);near(r.psus.p1.watts,60);near(r.psus.p3.watts,10);near(r.banks['c1:0'].amps,5);near(r.distros.d1.amps,10/12);assert.equal(r.distros.d1.feeds,1);near(r.chains.test.segments[1].endV,12-2*2*.02095*(10/12));
seed.inject=true;seed.psu='p4';seed.distro='d2';r=calculate(p);near(r.banks['c1:0'].amps,0);near(r.psus.p4.watts,60);
p.brightness=40;r=calculate(p);near(r.watts,28);near(r.fullWatts,70);near(Object.values(r.psus).reduce((n,x)=>n+x.watts,0),r.watts);
seed.count=1000;r=calculate(p);assert.ok(r.warnings.some(w=>w.title==='Controller channel limit'));
p.psus.find(s=>s.id==='p4').watts=10;r=calculate(p);assert.ok(r.warnings.some(w=>w.title.endsWith('over capacity')));
assert.equal(bankFor({model:'b8'},4),0);assert.equal(bankFor({model:'b8'},5),1);assert.equal(bankFor({model:'b17'},17),4);
const bad=tailoredInitial();bad.chains[0].segments[0].count=-1;assert.throws(()=>validateProject(bad));
const bad2=tailoredInitial();bad2.chains[0].segments[0].inject=true;bad2.chains[0].segments[0].psu='wrong';assert.throws(()=>validateProject(bad2));
const good=tailoredInitial();validateProject(good);assert.deepEqual(validateProject(JSON.parse(JSON.stringify(good))),good);
console.log('Passed: mixed loads, loop drop, distributed wire drop, isolated injection allocation, distro-only ports, brightness/full-white, capacity/channel checks, port banks, JSON round-trip and invalid input rejection.');
const plan=recommendSections(tailoredInitial(),'r1',0,'d1');
assert.ok(plan.addedFeeds>0);assert.equal(plan.sections.reduce((n,s)=>n+s.count,0),200);
const pr=calculate(plan.project);assert.ok(pr.chains.r1.segments.every(s=>s.dropPct<=10));near(pr.watts,220);assert.equal(pr.chains.r1.channels,600);
const impossible=tailoredInitial();impossible.chains[0].segments[0].leadM=10000;assert.throws(()=>recommendSections(impossible,'r1',0,'d1'));
console.log('Passed: injection recommendations conserve device count, channels and power, meet the drop target, and reject impossible feeds. Boundaries:',JSON.stringify(plan.sections));
const legacy=tailoredInitial(),before=calculate(legacy);ensureScene(legacy);validateProject(legacy);assert.equal(calculate(legacy).watts,before.watts);assert.equal(calculate(legacy).channels,before.channels);
legacy.scene.placements['controller:c1'].x=8;ensureScene(legacy);assert.equal(legacy.scene.placements['controller:c1'].x,8);
for(const shape of ['smiley','circle','star','line','grid'])for(const count of [1,2,64,150]){const dots=pixelPoints({...makeProp(shape),shape,count});assert.equal(dots.length,count);assert.ok(dots.every(pt=>pt.x>=0&&pt.x<=1&&pt.y>=0&&pt.y<=1));}
assert.deepEqual(clampPosition({x:-8,y:99},legacy.scene),{x:0,y:8});
const round=JSON.parse(JSON.stringify(legacy));validateProject(round);assert.deepEqual(round.scene,legacy.scene);assert.deepEqual(round.props,legacy.props);
const invalid=structuredClone(legacy);invalid.props[0].reference='data:image/svg+xml,<svg onload="bad"/>';assert.throws(()=>validateScene(invalid));
const invalidPos=structuredClone(legacy);invalidPos.scene.placements['controller:c1'].x=-1;assert.throws(()=>validateScene(invalidPos));
console.log('Passed: legacy project migration, retained positions, pixel geometry counts/bounds, layout JSON round-trip and unsafe image/position rejection.');
const wiring=tailoredInitial();validateProject(wiring);connectWire(wiring,'psu:p3:2','bank:c1:1');assert.equal(wiring.controllers[0].bankPsus[0],'p3');assert.equal(wiring.controllers[0].bankPsuPorts[0],2);connectWire(wiring,'distro:d1:2',`power:${wiring.chains[0].segments[0].id}`);assert.equal(wiring.chains[0].segments[0].distroPort,2);assert.equal(wiring.chains[0].segments[0].inject,true);assert.equal(calculate(wiring).psus.p3.watts>0,true);assert.throws(()=>connectWire(wiring,'psu:p3:1','bank:c1:2'));const blank={version:1,name:'Untitled project',brightness:100,headroom:80,dropLimit:10,startChannel:1,psus:[],distros:[],controllers:[],chains:[],presets:[],aux:[],props:[],scene:{width:12,depth:8,snap:.1,placements:{}}};validateProject(blank);assert.equal(calculate(blank).watts,0);
console.log('Passed: graph connection assignments, occupied-terminal rejection and blank project.');
const order=tailoredInitial();validateProject(order);const first=order.chains[0].segments[0].id,other=order.chains[2].segments[0].id;connectWire(order,`data-out:${first}`,`data-in:${other}`);assert.equal(order.chains[0].segments[1].id,other);assert.equal(order.chains.some(ch=>ch.id==='r3'),false);validateProject(order);
console.log('Passed: dragging pixel data output onto another group updates chain order.');
const pwr=tailoredInitial();validateProject(pwr);const tail=newSegment();tail.inject=true;tail.psu='p3';tail.distro='d1';pwr.chains[0].segments.push(tail);validateProject(pwr);connectWire(pwr,`power-out:${pwr.chains[0].segments[0].id}`,`power:${tail.id}`);assert.equal(tail.inject,false);validateProject(pwr);
console.log('Passed: reconnecting consecutive pixel groups restores upstream power.');
